# Generated by Django 4.2.2 on 2024-07-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_username_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_adress',
            field=models.CharField(default='Default wallet address', max_length=100),
        ),
    ]
