# Generated by Django 4.2.2 on 2024-07-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_wallet_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wallet_adress',
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(default='Default wallet adress', max_length=100),
        ),
    ]
